// Build-time content generator. Walks the consumer's `content/docs/` tree,
// captures each MDX file's frontmatter + raw source + slug + href, reads
// `_meta.json`, and emits a TypeScript module that registers the snapshot
// with the runtime cache.
//
// Output: `<consumer>/lib/doks-content.gen.ts`. The consumer's
// `app/layout.tsx` adds a side-effect `import "@/lib/doks-content.gen";`
// so the registration happens before any page renders. After registration,
// `getDocBySlug`, `getAllDocs`, `getDocSource`, and `buildDocTree` all
// resolve from memory — no fs at request time, which lets edge runtimes
// (Cloudflare Workers, Vercel Edge, etc.) serve doc pages.

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

import { CONTENT_SCHEMA_VERSION } from '../runtime/content';
import type { DocFrontmatter } from '../lib/docs';

export interface BuildContentOptions {
  /** Project root. Defaults to `process.cwd()`. */
  root?: string;
  /** Path (relative to `root`) to the docs corpus. Defaults to `content/docs`. */
  docsDir?: string;
  /** Path (relative to `root`) to write the generated module. Defaults to `lib/doks-content.gen.ts`. */
  outFile?: string;
  /** Suppress stdout. Default `false`. */
  silent?: boolean;
}

interface CapturedDoc {
  slug: string[];
  href: string;
  frontmatter: DocFrontmatter;
  raw: string;
  filePath: string;
}

function walkMdx(dir: string, files: string[] = []): string[] {
  if (!fs.existsSync(dir)) return files;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walkMdx(full, files);
    else if (/\.mdx?$/.test(entry.name)) files.push(full);
  }
  return files;
}

function fileToSlug(filePath: string, docsDir: string): string[] {
  const rel = path.relative(docsDir, filePath);
  const noExt = rel.replace(/\.(md|mdx)$/, '');
  const parts = noExt.split(path.sep);
  if (parts[parts.length - 1] === 'index') parts.pop();
  return parts;
}

export function buildContent(options: BuildContentOptions = {}): { docs: number; outFile: string } {
  const root = options.root ?? process.cwd();
  const docsDir = path.resolve(root, options.docsDir ?? 'content/docs');
  const outFile = path.resolve(root, options.outFile ?? 'lib/doks-content.gen.ts');
  const log = options.silent ? () => {} : (m: string) => console.log(m);

  log('▸ doks build:content');
  log(`  docs:   ${path.relative(root, docsDir) || '.'}`);
  log(`  output: ${path.relative(root, outFile) || '.'}`);

  if (!fs.existsSync(docsDir)) {
    log(`  ⚠ docs directory not found, writing empty content map`);
  }

  const files = walkMdx(docsDir);
  const captured: CapturedDoc[] = files.map((filePath) => {
    const raw = fs.readFileSync(filePath, 'utf8');
    const { data } = matter(raw);
    const slug = fileToSlug(filePath, docsDir);
    return {
      slug,
      href: '/docs' + (slug.length ? '/' + slug.join('/') : ''),
      frontmatter: data as DocFrontmatter,
      raw,
      filePath,
    };
  });

  const metaPath = path.join(docsDir, '_meta.json');
  let rootMeta: Record<string, unknown> = {};
  if (fs.existsSync(metaPath)) {
    try {
      rootMeta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
    } catch (err) {
      log(`  ⚠ failed to parse ${metaPath}: ${(err as Error).message}`);
    }
  }

  const payload = {
    schemaVersion: CONTENT_SCHEMA_VERSION,
    docs: captured.map((c) => ({
      slug: c.slug,
      href: c.href,
      frontmatter: c.frontmatter,
      raw: c.raw,
      filePath: c.filePath,
    })),
    rootMeta,
  };

  // Use JSON.stringify (not template literal interpolation) so backticks,
  // backslashes, and Unicode in MDX bodies survive intact.
  const body =
    `// AUTO-GENERATED by \`doks build:content\`. Do not edit.\n` +
    `// Re-runs on \`predev\` and \`prebuild\`; see your package.json.\n` +
    `\n` +
    `import { setContentMap } from "doks-core/runtime/content";\n` +
    `\n` +
    `setContentMap(${JSON.stringify(payload)});\n` +
    `\n` +
    `export {};\n`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body);

  log(`  ✓ captured ${captured.length} doc(s)`);
  return { docs: captured.length, outFile };
}

// CLI entrypoint.
const isMain =
  typeof process !== 'undefined' &&
  process.argv[1] !== undefined &&
  /scripts[\\/]buildContent\.[mc]?[jt]s$/.test(process.argv[1]);

if (isMain) {
  try {
    buildContent();
  } catch (err) {
    console.error('build:content failed:', err);
    process.exit(1);
  }
}
